"""
Reviewer Agent Module

Responsibility: Evaluate the Generator Agent's output for quality.

The Reviewer Agent assesses generated educational content against:
- Age appropriateness for the specified grade
- Conceptual correctness
- Clarity of explanation and questions
"""

import json
import re
from typing import Literal
from pydantic import BaseModel, Field

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config import generate_completion


# ============================================================================
# Data Models (Structured Input/Output)
# ============================================================================

class ReviewerInput(BaseModel):
    """Input for the Reviewer Agent - the Generator's output plus context."""
    grade: int = Field(..., ge=1, le=12, description="Target grade level")
    topic: str = Field(..., description="Topic being covered")
    explanation: str = Field(..., description="Generated explanation")
    mcqs: list[dict] = Field(..., description="Generated MCQs")


class ReviewerOutput(BaseModel):
    """Structured output from the Reviewer Agent."""
    status: Literal["pass", "fail"]
    feedback: list[str] = Field(default_factory=list)


# ============================================================================
# Reviewer Agent Implementation
# ============================================================================

class ReviewerAgent:
    """
    Agent responsible for reviewing educational content quality.
    
    This agent evaluates content generated by the Generator Agent
    to ensure it meets quality standards for the target grade level.
    """
    
    def __init__(self):
        """Initialize the Reviewer Agent."""
        pass
    
    def _build_prompt(self, input_data: ReviewerInput) -> str:
        """Build the review prompt for the LLM."""
        mcqs_formatted = json.dumps(input_data.mcqs, indent=2)
        
        prompt = f"""Evaluate the following educational content:

**Target Grade:** {input_data.grade}
**Topic:** {input_data.topic}

**Explanation:**
{input_data.explanation}

**Multiple Choice Questions:**
{mcqs_formatted}

**Evaluation Criteria:**
1. **Age Appropriateness:** Is the language suitable for grade {input_data.grade}?
2. **Conceptual Correctness:** Are all facts and concepts accurate?
3. **Clarity:** Is the content easy to understand?

**Instructions:**
- Return "pass" if the content meets ALL criteria satisfactorily
- Return "fail" if ANY significant issues are found
- Provide specific, actionable feedback for any issues found

**Output Format:**
Return ONLY a valid JSON object (no markdown, no code blocks, no extra text):
{{
    "status": "pass" or "fail",
    "feedback": ["<specific issue 1 if any>", "<specific issue 2 if any>"]
}}
"""
        return prompt
    
    def _parse_response(self, response_text: str) -> ReviewerOutput:
        """Parse the LLM response into structured output."""
        cleaned = response_text.strip()
        
        if cleaned.startswith("```json"):
            cleaned = cleaned[7:]
        elif cleaned.startswith("```"):
            cleaned = cleaned[3:]
        if cleaned.endswith("```"):
            cleaned = cleaned[:-3]
        cleaned = cleaned.strip()
        
        json_match = re.search(r'\{[\s\S]*\}', cleaned)
        if json_match:
            cleaned = json_match.group()
        
        try:
            data = json.loads(cleaned)
            if "status" in data:
                data["status"] = data["status"].lower()
            return ReviewerOutput(**data)
        except (json.JSONDecodeError, Exception) as e:
            raise ValueError(f"Failed to parse reviewer response: {e}")
    
    def review(self, input_data: ReviewerInput) -> ReviewerOutput:
        """Review educational content for quality."""
        prompt = self._build_prompt(input_data)
        system_prompt = "You are an expert educational content reviewer. Always respond with valid JSON only."
        response = generate_completion(prompt, system_prompt)
        
        return self._parse_response(response)
    
    def review_from_dict(self, generator_output: dict, grade: int, topic: str) -> dict:
        """Convenience method to review from dict and return dict."""
        input_data = ReviewerInput(
            grade=grade,
            topic=topic,
            explanation=generator_output.get("explanation", ""),
            mcqs=generator_output.get("mcqs", [])
        )
        output = self.review(input_data)
        return output.model_dump()
